### ISSUE TITLE
How to specify pattern string in config?

### ISSUE THREAD

**Issue by i-am-phi** [hexojs/hexo-filter-responsive-images#12]
I have installed this plugin and added parameters to the _config.yml but I see no additional files under the `public` folder after running `hexo generate`.  I suspect the pattern is not correct. In the readme file, you show example patterns as:
```
  pattern: content/**/*.+(png|jpg|jpeg)
```
In my Hexo install, I have a 'source' folder, not 'content.' But, specifying the following does nothing. 
```
responsive_images:
  pattern: source/**/*.+(png|jpg|jpeg)
  sizes:
    small:
      width: 800
    medium:
      width: 1200
    large:
      width: 2000
```
Being able to create multiple versions of images would be fantastic. I hope we can figure this out. 

- phi
